### PR TITLE
Options to control logging

### PR DESCRIPTION
**Pull request by goetzk**
To enable easier debugging of squid problems extra configurability of the
logging system can be helpful.

This change adds controls for various options including log level, location and
format.

Relates to #10

### CODE REVIEW

**Comment by goetzk** [comment]
These Travis failures do not appear to be PR related.

**Comment by mrlesmithjr** [comment]
@goetzk Can you rebase with master to get the latest updated CI tests?

**Comment by mrlesmithjr** [comment]
Fails on:
```bash
    TASK [ansible-squid : config_squid | Configuring Squid] ************************
fatal: [centos8]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'squid_debug_options' is undefined"}
```
This is the same for each distro.

**Comment by goetzk** [comment]
Embarrassingly I forgot the 'is defined' check. Hopefully the new version will DTRT; I'll check travis soon.

**Comment by goetzk** [comment]
Think we're ok this time!

**Pull request merged**
